String management
Purdue-ACM-SIGAPP/PurdueLaundry pull request #44
Opened 2016-10-18 21:09 UTC by vidia

Moved strings to static final references. There were too many raw references to Strings all over. This collects them into one place.

2016-10-18 21:11 UTC, vidia reviewed
This PR isnt complete. It needs to fix a few things that I have commented in the review. 

EDIT: The PR is now complete.

2016-10-18 21:11 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/adapters/MachineAdapter.java
> +        builder.setContentTitle("Purdue Laundry"); //TODO: Get string resource for App name.
This should ideally be pulled out into a string reference.

2016-10-18 21:11 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/fragments/MachineFragment.java
>      public static String options = "Available|In use|Almost done|End of cycle";
This set of options is scattered around the code. It should be collected into one place. 

What is it doing @hughesjeff ? Did you write these parts?

2016-10-19 08:51 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/fragments/MachineFragment.java
>      public static String options = "Available|In use|Almost done|End of cycle";
Fixed it. Its the filter options. I pulled them out, but it still works the same.

2016-10-20 00:24 UTC, hughesjeff commented
Doesn't compile. Please fix  last comment.

2016-10-20 00:24 UTC, hughesjeff requested changes

2016-10-20 00:24 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/LaundryParser/MachineTypes.java
> +    public static final String DRYER = "Dryer";
Should probably move these into strings.xml, but it works for now so we can get a release out.

2016-10-20 00:24 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/LaundryParser/MachineStates.java
> +    public static final String IN_USE = "In use";
Should probably move these into strings.xml, but it works for now so we can get a release out.

2016-10-20 00:24 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/LaundryParser/Rooms.java
> +        machineAvailabilityColors.put(MachineStates.AVAILABLE, R.color.Available);
Literally what strings.xml was made for :P

2016-10-20 00:24 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/fragments/MachineFragment.java
> -    public static String options = "Available|In use|Almost done|End of cycle";
This was used... Won't compile without.

2016-10-20 01:09 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/LaundryParser/MachineTypes.java
> +    public static final String DRYER = "Dryer";
I really do want to have this in Strings.xml. The issue is that there isnt always a context available when we want access to these. 

I also want an overhaul of things a bit .

2016-10-20 01:36 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/LaundryParser/Rooms.java
> +        machineAvailabilityColors.put(MachineStates.AVAILABLE, R.color.Available);
Yeah, But again the lack of a context in all relevant places makes it rough. We may need to init these in Activity.onCreate() and then access statically like this. But even that isnt COMPLETELY ideal.

2016-10-24 07:27 UTC, merged