Pulltorefresh
Purdue-ACM-SIGAPP/PurdueLaundry pull request #50
Opened 2016-10-19 18:39 UTC by vidia

Added the Pull to refresh functionality. 

Removed the fallback calls that used "Cary West" instead of null. I now throw an exception if that happens, which should make sure that it will never happen when we test.

2016-10-19 18:40 UTC, vidia commented
Completes #46

2016-10-19 20:55 UTC, vidia commented
In true terrible non-atomic PR fashion, I am ALSO removing the reliance on SharedPrefs for tracking the lastRoom with this.

2016-10-20 00:25 UTC, hughesjeff requested changes
This also doesn't compile because a needed method was removed.

2016-10-20 00:25 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/activities/MachineActivity.java
> -    public static String getSelected() {
So uh, this method is kinda necessary...

2016-10-20 00:25 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/activities/MachineActivity.java
> -    private static String currentRoom;
Should be static

2016-10-20 00:28 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/activities/MachineActivity.java
> -    public static String getSelected() {
Fixed it. I didnt re-add it, but I removed the reference to it. I didnt like it being static.

2016-10-20 01:39 UTC, hughesjeff approved these changes

2016-10-21 00:22 UTC, merged