No static filters
Purdue-ACM-SIGAPP/PurdueLaundry pull request #95
Opened 2017-02-10 18:27 UTC by bienzaaron

Added a MachineFilter class to handle filtering machines outside of MachineFragment. When the filter is updated by the user, a new MachineFilter object is created and converted into JSON then stored in SharedPreferences. When the list of machines is updated(in MachineAdapter), the MachineFilter object is retrieved from SharedPreferences and filters the machines appropriately. Also fixed some issues with the notify button that I ran into while testing filtering.

2017-02-10 21:51 UTC, vidia reviewed
Looking good.

2017-02-10 21:51 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/MachineFilter.java
> +        IN_USE(MachineStates.IN_USE), AVAILABLE(MachineStates.AVAILABLE),
Thank you for these.... They have been necessary for too long.

2017-02-10 21:51 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/MachineFilter.java
> +            if(stateString.equalsIgnoreCase(MachineStates.IN_USE)) return IN_USE;
Since you stored the strings in the enum, can you loop it instead?

2017-02-10 21:51 UTC, vidia commented on app/src/main/java/xyz/jhughes/laundry/activities/MachineActivity.java
> +                        AnalyticsHelper.sendEventHit("Filters", AnalyticsHelper.CLICK, MachineFilter.State.toString(states));
states here is the list of enabled states?

2017-02-10 22:31 UTC, bienzaaron commented on app/src/main/java/xyz/jhughes/laundry/MachineFilter.java
> +            if(stateString.equalsIgnoreCase(MachineStates.IN_USE)) return IN_USE;
will do

2017-02-10 22:31 UTC, bienzaaron commented on app/src/main/java/xyz/jhughes/laundry/activities/MachineActivity.java
> +                        AnalyticsHelper.sendEventHit("Filters", AnalyticsHelper.CLICK, MachineFilter.State.toString(states));
correct

2017-02-15 00:05 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/fragments/MachineFragment.java
> +                    postSnackbar("No machines to set a timer for!", Snackbar.LENGTH_LONG);
Could we move this to strings.xml? I know it wasn't there to begin with. Blame Pitlor.

2017-02-15 00:09 UTC, hughesjeff commented
Can you add a check for someone unchecking all the boxes? It shows the button. Maybe show an error saying something along the lines of "Your filters don't allow any machines to be shown. Please select some machines to show" or similar.

Looks good overall. Just fix those few things, and we'll go ahead and merge.

2017-02-15 00:10 UTC, hughesjeff requested changes

2017-02-15 00:10 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/fragments/MachineFragment.java
> +                        int machTime = Integer.parseInt(mach.getTime().substring(0, mach.getTime().indexOf(' ')));
Please expand to "machineTime"

2017-02-15 00:52 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/activities/MachineActivity.java
> +                        for(MachineFilter.State s : states) {
Debug code.

2017-02-15 00:52 UTC, hughesjeff commented on app/src/main/java/xyz/jhughes/laundry/MachineFilter.java
> -        READY(MachineStates.READY);
Good catch, since we don't really use this lol

2017-02-15 00:56 UTC, hughesjeff approved these changes

2017-02-15 00:56 UTC, merged